# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-03 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256)),
                ('is_finish', models.BooleanField(default=False)),
                ('isEditing', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
                ('isChecked', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
